# Generated by Django 4.2.26 on 2025-11-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Joueur'), ('organisateur', 'Organisateur')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
