# Generated by Django 5.0.1 on 2025-11-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Joueur'), ('organizer', 'Organisateur')], max_length=20),
        ),
    ]
