# Generated by Django 5.0.1 on 2025-11-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'tournament', 'verbose_name_plural': 'tournaments'},
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
        migrations.AlterModelTable(
            name='tournament',
            table='tournaments',
        ),
    ]
