# Generated by Django 5.0.1 on 2025-11-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'match', 'verbose_name_plural': 'matches'},
        ),
        migrations.AlterModelTable(
            name='match',
            table='matches',
        ),
    ]
