# Generated by Django 5.0.1 on 2025-11-21 21:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending ', 'En attente '), ('accepted ', 'Accepte '), ('rejected ', 'Refuse ')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests_as_player', to='accounts.user')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests_as_team', to='tournaments.team')),
            ],
            options={
                'db_table': 'requestes',
                'unique_together': {('player', 'team')},
            },
        ),
    ]
