# Generated by Django 5.0.1 on 2025-11-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestes', '0002_alter_joinrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'verbose_name': 'requeste', 'verbose_name_plural': 'requestes'},
        ),
    ]
