# Generated by Django 4.2.16 on 2025-11-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('favorite_sport', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('beginner ', 'Debutant '), ('intermediate ', 'Intermediaire '), ('advanced ', 'Avance ')], max_length=20)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'player_profiles ',
            },
        ),
    ]
