# Generated by Django 4.2.26 on 2025-11-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='level',
            field=models.CharField(choices=[('beginner', 'Debutant'), ('intermediate', 'Intermediaire'), ('advanced', 'Avance')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='playerprofile',
            table='player_profiles',
        ),
    ]
