# Generated by Django 5.0.1 on 2025-11-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_playerprofile_level_alter_playerprofile_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerprofile',
            options={'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
    ]
